CREATE TABLE IF NOT EXISTS market_snapshots (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  market_id VARCHAR(128) NOT NULL,
  market_name VARCHAR(255) NOT NULL,
  yes_price DECIMAL(8,4) NOT NULL,
  no_price DECIMAL(8,4) NOT NULL,
  volume_24h DECIMAL(20,4) NOT NULL DEFAULT 0,
  liquidity DECIMAL(20,4) NOT NULL DEFAULT 0,
  strategy_tag VARCHAR(64) NOT NULL,
  snapshot_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_market_snapshots_market_time (market_id, snapshot_at)
);

CREATE TABLE IF NOT EXISTS fills (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  market_id VARCHAR(128) NOT NULL,
  market_name VARCHAR(255) NOT NULL,
  side ENUM('Yes', 'No') NOT NULL,
  price DECIMAL(8,4) NOT NULL,
  size DECIMAL(20,4) NOT NULL,
  fee DECIMAL(20,4) NOT NULL DEFAULT 0,
  filled_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_fills_time (filled_at)
);

CREATE TABLE IF NOT EXISTS positions (
  id VARCHAR(64) PRIMARY KEY,
  market_id VARCHAR(128) NOT NULL,
  market_name VARCHAR(255) NOT NULL,
  side ENUM('Yes', 'No') NOT NULL,
  size DECIMAL(20,4) NOT NULL,
  entry_price DECIMAL(8,4) NOT NULL,
  current_price DECIMAL(8,4) NOT NULL,
  unrealized_pnl DECIMAL(20,4) NOT NULL DEFAULT 0,
  realized_pnl DECIMAL(20,4) NOT NULL DEFAULT 0,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_positions_market (market_id)
);

CREATE TABLE IF NOT EXISTS strategy_configs (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  strategy_name VARCHAR(64) NOT NULL UNIQUE,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  params_json JSON NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS risk_rules (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  rule_name VARCHAR(64) NOT NULL UNIQUE,
  rule_value VARCHAR(128) NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS risk_events (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  event_type VARCHAR(64) NOT NULL,
  severity ENUM('LOW', 'MEDIUM', 'HIGH', 'CRITICAL') NOT NULL,
  message VARCHAR(512) NOT NULL,
  context_json JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_risk_events_time (created_at)
);

CREATE TABLE IF NOT EXISTS system_metrics (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  cpu_pct DECIMAL(6,2) NOT NULL,
  mem_mb DECIMAL(10,2) NOT NULL,
  api_latency_ms DECIMAL(10,2) NOT NULL,
  recorded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_system_metrics_time (recorded_at)
);

CREATE TABLE IF NOT EXISTS system_logs (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  level VARCHAR(16) NOT NULL,
  category VARCHAR(64) NOT NULL,
  message VARCHAR(1024) NOT NULL,
  context_json JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_system_logs_time (created_at)
);

CREATE TABLE IF NOT EXISTS api_credentials (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  provider VARCHAR(64) NOT NULL,
  key_id VARCHAR(255) NULL,
  ciphertext TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_provider (provider)
);
